### ISSUE TITLE
Starlette Config

### ISSUE THREAD

**Issue by guscardvs** [rednafi/fastapi-nano#104]
Would make sense to use `starlette.config.Config` instead of `os.environ` + `load_dotenv`?
Starlette Config does env validation and has builtin load dotenv which would remove the need for python-dotenv.
I could send a pull request if its fine.

**Comment by rednafi** [comment]
Seems like a neat idea. I'd love to see the implementation at work.

**Comment by guscardvs** [comment]
Closed by PR #105
