### ISSUE TITLE
Counterproductive use of async routes in auth?

### ISSUE THREAD

**Issue by phdowling** [rednafi/fastapi-nano#271]
Hi, I was just browsing through this repo and noticed that the auth routes are declared using `async def`, in https://github.com/rednafi/fastapi-nano/blob/master/app/core/auth.py#L125 but the underlying database access in the function that is also used as a dependency on line https://github.com/rednafi/fastapi-nano/blob/master/app/core/auth.py#L117 is synchronous. My understanding of FastAPI is such that in this case, it would be better to declare the route and dependency using a simple `def`, so that the whole thing is handled in a thread and other requests can still be processed concurrently. The way it's currently implemented, I think the entire event loop might be blocked whenever the database is accessed in that route and the related dependency. 

Just flagging out of interest, apologies if my understanding is incorrect here.

**Comment by rednafi** [comment]
@phdowling This is a mistake. Thank you for catching that. Care to send a PR? The tests might need some work too.

**Comment by kareemmahlees** [comment]
@rednafi would like to work on that, if you could assign to me 🙂

**Comment by rednafi** [comment]
@kareemmahlees Thanks, you can get started now.
