### ISSUE TITLE
Add logging- Feature request

### ISSUE THREAD

**Issue by dojowahi** [rednafi/fastapi-nano#278]
If we add how logging can be incorporated, when API calls are made, using middleware it will cover all facets.

**Comment by rednafi** [comment]
Indeed. I’m curious to see what you have in mind. Would you like to work on that? It’ll need tests too.

**Comment by dojowahi** [comment]
I was thinking of having a logging.conf, and then building off it in different modules.  A separate folder for middleware, which automatically gets called before and after and after API call is made. It has some sort of  unique ID for each request so you can trace which logs come from the same requests, and also time taken by API

**Comment by rednafi** [comment]
Not a bad idea. I have to see the first pass to make a comment on that.

**Comment by priamai** [comment]
+1 on this is amazing!

**Comment by rednafi** [comment]
A basic logged added. 

https://github.com/rednafi/fastapi-nano/pull/316
