### ISSUE TITLE
WARNING: Failed to generate report: No data to report.

### ISSUE THREAD

**Issue by priamai** [rednafi/fastapi-nano#315]
Hello,
when I run make test:
```
tests/test_apis.py::test_api_a_unauthorized FAILED                                                                      [  6%]/home/robomotic/DevOps/github/fastapi-nano/.venv/lib/python3.13/site-packages/coverage/inorout.py:505: CoverageWarning: Module src was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/robomotic/DevOps/github/fastapi-nano/.venv/lib/python3.13/site-packages/coverage/control.py:892: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
WARNING: Failed to generate report: No data to report.

```
can you explain what should be done to generate a proper coverage report?
How do we enable the data collection?

**Comment by rednafi** [comment]
Interesting, the `make test` command doesn’t have coverage anywhere. What command are you running to get this?

**Comment by rednafi** [comment]
Do you have uv installed and configured properly? The CI runs `make test` and it works without any error. So I couldn’t reproduce it.

**Comment by priamai** [comment]
Yes fresh git clone with UV installed and I get that error. Very weird.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rednafi** [comment]
I was able to reproduce it. This has been patched. Thanks for reporting. 

https://github.com/rednafi/fastapi-nano/pull/316
