### ISSUE TITLE
Live reload Option 

### ISSUE THREAD

**Issue by sunil-sq** [rednafi/fastapi-nano#4]
Hi,
I am trying to use live reload for devlepement. I have added below code in Dockerfile as suggested in uvicorn-gunicorn-fastapi-docker. But when i check it still takes start.sh. Any idea? Thank you very much.

```
RUN pip install -r requirements.txt

# copy project
COPY . /code/

CMD [ "/start-reload.sh" ]  # <-----

# expose port
EXPOSE 5000
```

**Comment by rednafi** [comment]
I don't recommend overriding the uvicorn-gunicorn-fastapi-docker image's default `start.sh` because it not being only runs uvicorn with gunicorn but also does other optimization. Instead, for development, try running it without docker or with your own separate docker image.

**Comment by sunil-sq** [comment]
Thank you.. I will do as per your suggestion.

**Comment by limsammy** [comment]
See my PR #6 for running locally (includes live reload)
