### ISSUE TITLE
Helmchart for Kubernetes

### ISSUE THREAD

**Issue by ayr-ton** [rednafi/fastapi-nano#57]
Would fit contributing with helm chart from Kubernetes workloads?

I have a very simple one that is very portable.

**Comment by ayr-ton** [comment]
@rednafi closing is a no?

**Comment by rednafi** [comment]
Accidentally closed this, apologies. Unfortunately, I'm not too familiar with Kubernetes workflow and would like to keep this as thin as possible.

**Comment by ayr-ton** [comment]
@rednafi Let me send a small PR so you can review. I can follow the thin as possible idea with it.

**Comment by rednafi** [comment]
@ayr-ton Let's do that and try to keep it as decoupled as possible. We can iterate from there if you're interested.

**Comment by rednafi** [comment]
No progress here. Closing.
