### ISSUE TITLE
GitHub Actions publish

### ISSUE THREAD

**Issue by ayr-ton** [rednafi/fastapi-nano#58]
What about a GitHub Action that publishes the Docker container to the GitHub repository registry?

**Comment by rednafi** [comment]
This is a great idea but I'm not sure how it'd be helpful when you'll need access to the code.

**Comment by ayr-ton** [comment]
@rednafi Access to the code how? Could you elaborate?

**Comment by rednafi** [comment]
@ayr-ton This application is pretty basic at what it does. However, it's extensible. So, if I push this as a container, what purpose that'd serve? I mean in the end, you'll need access to the code in the container and if you docker-pull the container, you won't have access to the source code. 

I mean, it's easy enough to push the container but I was wondering what purpose that'd serve.

**Comment by ayr-ton** [comment]
@rednafi Got it!
I think in 2 advantages:
- Testing the container build itself (we could actually test it with testinfra for validating aspects of the container creation)
- Have a reference pipeline on how to push the container to a registry (either GitHub or https://ttl.sh/)

Also, we could publish it to dockerhub if we want so anyone could pull the image for validating the working architecture.

If someone chooses to use some container scheduler in the future, this someone would just need to track the container registry for having updates (Ex.: ArgoCD).

**Comment by rednafi** [comment]
I think you've convinced me. So, what I'll do is to push the container to GitHub registry and then see if anyone finds that useful. Thank you.

**Comment by rednafi** [comment]
After battling with the CI, this is now ready. Checkout the release for details.
