### ISSUE TITLE
How to use authorization token to login instead of using username+password?

### ISSUE THREAD

**Issue by JohnnyRacer** [rednafi/fastapi-nano#78]
Hi, I couldn't seem to find any documentation specifiying how to login with the access token instead of regular auth scheme?

**Comment by rednafi** [comment]
@JohnnyRacer This authorization is meant to work as a simple placeholder for something that's going to be overwritten in a production application. Auth is a large and mostly complex topic. FastAPI doc has some pointers on how you can implement token-based auth.

https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/?h=

**Comment by JohnnyRacer** [comment]
@rednafi  Thank you so much for pointing me in the right direction! Much appreciated.
